<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation for {name}' => 'Активация для {name}',
    'Articles' => 'Статьи',
    'Articles category &laquo;{title}&raquo;' => 'Статьи категории &laquo;{title}&raquo;',
    'Articles tagged with &laquo;{name}&raquo;' => 'Статьи с тегом &laquo;{name}&raquo;',
    'Backend' => 'Панель управления',
    'Birthday' => 'День рождения',
    'Change password' => 'Сменить пароль',
    'Check your email for further instructions.' => 'Проверьте ваш email.',
    'Confirm password' => 'Подтвердите пароль',
    'Contact' => 'Контакты',
    'Email' => '',
    'Error activate your account.' => 'Ошибка активации аккаунта.',
    'Female' => 'Женский',
    'Firstname' => 'Имя',
    'Gender' => 'Пол',
    'Hello {username}, follow the link below to confirm your email:' => 'Привет {username}, перейдите по ссылке ниже, чтобы подтвердить ваш email:',
    'Hello {username}, follow the link below to reset your password:' => 'Привет {username}, перейдите по ссылке ниже, чтобы сбросить ваш пароль:',
    'Lastname' => 'Фамилия',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Lost password' => 'Восстановить пароль',
    'Male' => 'Мужской',
    'Name' => 'Имя',
    'New password saved.' => 'Новый пароль сохранен.',
    'Other' => 'Прочее',
    'Page not found.' => 'Страница не найдена.',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Сброс пароля для {name}',
    'Password reset token cannot be blank.' => 'Маркер восстановление пароля не может быть пустым.',
    'Registration is disabled.' => 'Регистрация отключена.',
    'Request password reset' => 'Запрос сброса пароля',
    'Reset password' => 'Сброс пароля',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Send email' => 'Отправить email',
    'Settings' => 'Настройки',
    'Signup' => 'Регистрация',
    'Sorry, we are unable to reset password for the provided email address.' => 'Извините, мы не можем сбросить пароль на указанный адрес электронной почты.',
    'Subject' => 'Тема',
    'Text' => 'Текст',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо. Мы свяжемся с вами в ближайшее время.',
    'There was an error sending your message.' => 'При отправке вашего сообщения произошла ошибка.',
    'Update' => 'Редактировать',
    'Username' => 'Имя пользователя',
    'Users' => 'Пользователи',
    'Verification code' => 'Проверочный код',
    'Website' => 'Веб-сайт',
    'Wrong password reset token.' => 'Неверный маркер сброса пароля.',
    'Your account has been successfully activated.' => 'Ваша учетная запись была успешно активирована.',
    'Your account has been successfully created. Check your email for further instructions.' => 'Ваша учетная запись была успешно создана. Проверьте свою электронную почту для получения дальнейших инструкций.',
    'Your message has been sent successfully.' => 'Ваше сообщение было успешно отправлено.',
    'Your password has been successfully changed.' => 'Ваш пароль был успешно изменен.',
];
